[2025-02-11T18:24:49.584+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T18:24:49.600+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T18:24:49.607+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T18:24:49.609+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T18:24:49.621+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_dim_location> on 2025-02-10 00:00:00+00:00
[2025-02-11T18:24:49.626+0000] {standard_task_runner.py:72} INFO - Started process 565 to run task
[2025-02-11T18:24:49.629+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_dim_location', 'scheduled__2025-02-10T00:00:00+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmp2hv45_mk']
[2025-02-11T18:24:49.631+0000] {standard_task_runner.py:105} INFO - Job 201: Subtask run_dbt_dim_location
[2025-02-11T18:24:49.648+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-11T18:24:49.682+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-10T00:00:00+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-11T18:24:49.683+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-11T18:24:49.755+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_dim_location' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-10T00:00:00+00:00'
[2025-02-11T18:24:49.756+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T18:24:49.769+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-11T18:24:49.770+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select dim_location']
[2025-02-11T18:24:49.779+0000] {subprocess.py:99} INFO - Output:
[2025-02-11T18:24:51.770+0000] {subprocess.py:106} INFO - [0m18:24:51  Running with dbt=1.9.2
[2025-02-11T18:24:52.080+0000] {subprocess.py:106} INFO - [0m18:24:52  Registered adapter: postgres=1.9.0
[2025-02-11T18:24:52.513+0000] {subprocess.py:106} INFO - [0m18:24:52  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-02-11T18:24:52.514+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-02-11T18:24:52.514+0000] {subprocess.py:106} INFO - - models.superstore_project.dim_product
[2025-02-11T18:24:52.697+0000] {subprocess.py:106} INFO - [0m18:24:52  Found 5 models, 8 data tests, 1 source, 431 macros
[2025-02-11T18:24:52.700+0000] {subprocess.py:106} INFO - [0m18:24:52
[2025-02-11T18:24:52.700+0000] {subprocess.py:106} INFO - [0m18:24:52  Concurrency: 1 threads (target='prod')
[2025-02-11T18:24:52.701+0000] {subprocess.py:106} INFO - [0m18:24:52
[2025-02-11T18:24:52.827+0000] {subprocess.py:106} INFO - [0m18:24:52  1 of 1 START sql incremental model core.dim_location ........................... [RUN]
[2025-02-11T18:24:53.026+0000] {subprocess.py:106} INFO - [0m18:24:53  1 of 1 OK created sql incremental model core.dim_location ...................... [[32mINSERT 0 2501[0m in 0.20s]
[2025-02-11T18:24:53.045+0000] {subprocess.py:106} INFO - [0m18:24:53
[2025-02-11T18:24:53.048+0000] {subprocess.py:106} INFO - [0m18:24:53  Finished running 1 incremental model in 0 hours 0 minutes and 0.34 seconds (0.34s).
[2025-02-11T18:24:53.110+0000] {subprocess.py:106} INFO - [0m18:24:53
[2025-02-11T18:24:53.111+0000] {subprocess.py:106} INFO - [0m18:24:53  [32mCompleted successfully[0m
[2025-02-11T18:24:53.112+0000] {subprocess.py:106} INFO - [0m18:24:53
[2025-02-11T18:24:53.112+0000] {subprocess.py:106} INFO - [0m18:24:53  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-11T18:24:54.020+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-11T18:24:54.073+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T18:24:54.074+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_dim_location, run_id=scheduled__2025-02-10T00:00:00+00:00, execution_date=20250210T000000, start_date=20250211T182449, end_date=20250211T182454
[2025-02-11T18:24:54.094+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T18:24:54.123+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T18:24:54.125+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
