[2025-02-11T18:25:28.479+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T18:25:28.493+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_date manual__2025-02-11T18:24:30.820415+00:00 [queued]>
[2025-02-11T18:25:28.500+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_date manual__2025-02-11T18:24:30.820415+00:00 [queued]>
[2025-02-11T18:25:28.501+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T18:25:28.513+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_dim_date> on 2025-02-11 18:24:30.820415+00:00
[2025-02-11T18:25:28.518+0000] {standard_task_runner.py:72} INFO - Started process 709 to run task
[2025-02-11T18:25:28.520+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_dim_date', 'manual__2025-02-11T18:24:30.820415+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpeq3f3vb3']
[2025-02-11T18:25:28.522+0000] {standard_task_runner.py:105} INFO - Job 206: Subtask run_dbt_dim_date
[2025-02-11T18:25:28.539+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-11T18:25:28.574+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_dim_date manual__2025-02-11T18:24:30.820415+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-11T18:25:28.642+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_dim_date' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T18:24:30.820415+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T18:24:30.820415+00:00'
[2025-02-11T18:25:28.644+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T18:25:28.659+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-11T18:25:28.661+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select dim_date']
[2025-02-11T18:25:28.670+0000] {subprocess.py:99} INFO - Output:
[2025-02-11T18:25:30.643+0000] {subprocess.py:106} INFO - [0m18:25:30  Running with dbt=1.9.2
[2025-02-11T18:25:30.916+0000] {subprocess.py:106} INFO - [0m18:25:30  Registered adapter: postgres=1.9.0
[2025-02-11T18:25:31.309+0000] {subprocess.py:106} INFO - [0m18:25:31  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-02-11T18:25:31.310+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-02-11T18:25:31.311+0000] {subprocess.py:106} INFO - - models.superstore_project.dim_product
[2025-02-11T18:25:31.510+0000] {subprocess.py:106} INFO - [0m18:25:31  Found 5 models, 8 data tests, 1 source, 431 macros
[2025-02-11T18:25:31.513+0000] {subprocess.py:106} INFO - [0m18:25:31
[2025-02-11T18:25:31.514+0000] {subprocess.py:106} INFO - [0m18:25:31  Concurrency: 1 threads (target='prod')
[2025-02-11T18:25:31.515+0000] {subprocess.py:106} INFO - [0m18:25:31
[2025-02-11T18:25:31.617+0000] {subprocess.py:106} INFO - [0m18:25:31  1 of 1 START sql incremental model core.dim_date ............................... [RUN]
[2025-02-11T18:25:31.952+0000] {subprocess.py:106} INFO - [0m18:25:31  1 of 1 OK created sql incremental model core.dim_date .......................... [[32mINSERT 0 0[0m in 0.33s]
[2025-02-11T18:25:31.970+0000] {subprocess.py:106} INFO - [0m18:25:31
[2025-02-11T18:25:31.971+0000] {subprocess.py:106} INFO - [0m18:25:31  Finished running 1 incremental model in 0 hours 0 minutes and 0.46 seconds (0.46s).
[2025-02-11T18:25:32.058+0000] {subprocess.py:106} INFO - [0m18:25:32
[2025-02-11T18:25:32.059+0000] {subprocess.py:106} INFO - [0m18:25:32  [32mCompleted successfully[0m
[2025-02-11T18:25:32.061+0000] {subprocess.py:106} INFO - [0m18:25:32
[2025-02-11T18:25:32.063+0000] {subprocess.py:106} INFO - [0m18:25:32  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-11T18:25:33.156+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-11T18:25:33.182+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T18:25:33.183+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_dim_date, run_id=manual__2025-02-11T18:24:30.820415+00:00, execution_date=20250211T182430, start_date=20250211T182528, end_date=20250211T182533
[2025-02-11T18:25:33.218+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T18:25:33.239+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T18:25:33.243+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
