[2025-01-18T08:40:05.770+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-18T08:40:05.783+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.extract_data manual__2025-01-18T08:40:02.777003+00:00 [queued]>
[2025-01-18T08:40:05.789+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.extract_data manual__2025-01-18T08:40:02.777003+00:00 [queued]>
[2025-01-18T08:40:05.790+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-18T08:40:05.801+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-01-18 08:40:02.777003+00:00
[2025-01-18T08:40:05.805+0000] {standard_task_runner.py:72} INFO - Started process 278 to run task
[2025-01-18T08:40:05.808+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'extract_data', 'manual__2025-01-18T08:40:02.777003+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpca3thc5s']
[2025-01-18T08:40:05.809+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask extract_data
[2025-01-18T08:40:05.823+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-18T08:40:05.853+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.extract_data manual__2025-01-18T08:40:02.777003+00:00 [running]> on host 9fe2ea257df4
[2025-01-18T08:40:05.923+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T08:40:02.777003+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-18T08:40:02.777003+00:00'
[2025-01-18T08:40:05.925+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-18T08:40:06.391+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-18T08:40:06.399+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-18T08:40:06.400+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=extract_data, run_id=manual__2025-01-18T08:40:02.777003+00:00, execution_date=20250118T084002, start_date=20250118T084005, end_date=20250118T084006
[2025-01-18T08:40:06.423+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-18T08:40:06.440+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-18T08:40:06.442+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
