[2025-02-16T17:45:27.798+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T17:45:27.819+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dm_categories_pivot_t manual__2025-02-16T17:44:13.179593+00:00 [queued]>
[2025-02-16T17:45:27.829+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dm_categories_pivot_t manual__2025-02-16T17:44:13.179593+00:00 [queued]>
[2025-02-16T17:45:27.830+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-16T17:45:27.841+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_dbt_dm_categories_pivot_t> on 2025-02-16 17:44:13.179593+00:00
[2025-02-16T17:45:27.847+0000] {standard_task_runner.py:72} INFO - Started process 1682 to run task
[2025-02-16T17:45:27.849+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_dm_categories_pivot_t', 'manual__2025-02-16T17:44:13.179593+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpkrkdkk_t']
[2025-02-16T17:45:27.851+0000] {standard_task_runner.py:105} INFO - Job 252: Subtask run_dbt_dm_categories_pivot_t
[2025-02-16T17:45:27.866+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-16T17:45:27.898+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_dm_categories_pivot_t manual__2025-02-16T17:44:13.179593+00:00 [running]> on host e06c424a4719
[2025-02-16T17:45:27.971+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_dm_categories_pivot_t' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T17:44:13.179593+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T17:44:13.179593+00:00'
[2025-02-16T17:45:27.972+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-16T17:45:27.986+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-16T17:45:27.987+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select categories_pivot_t']
[2025-02-16T17:45:27.996+0000] {subprocess.py:99} INFO - Output:
[2025-02-16T17:45:30.086+0000] {subprocess.py:106} INFO - [0m17:45:30  Running with dbt=1.9.2
[2025-02-16T17:45:30.394+0000] {subprocess.py:106} INFO - [0m17:45:30  Registered adapter: postgres=1.9.0
[2025-02-16T17:45:32.168+0000] {subprocess.py:106} INFO - [0m17:45:32  Found 7 models, 34 data tests, 1 source, 632 macros
[2025-02-16T17:45:32.172+0000] {subprocess.py:106} INFO - [0m17:45:32
[2025-02-16T17:45:32.176+0000] {subprocess.py:106} INFO - [0m17:45:32  Concurrency: 1 threads (target='prod')
[2025-02-16T17:45:32.178+0000] {subprocess.py:106} INFO - [0m17:45:32
[2025-02-16T17:45:32.296+0000] {subprocess.py:106} INFO - [0m17:45:32  1 of 1 START sql incremental model dm.categories_pivot_t ....................... [RUN]
[2025-02-16T17:45:32.534+0000] {subprocess.py:106} INFO - [0m17:45:32  1 of 1 OK created sql incremental model dm.categories_pivot_t .................. [[32mINSERT 0 14[0m in 0.23s]
[2025-02-16T17:45:32.550+0000] {subprocess.py:106} INFO - [0m17:45:32
[2025-02-16T17:45:32.551+0000] {subprocess.py:106} INFO - [0m17:45:32  Finished running 1 incremental model in 0 hours 0 minutes and 0.37 seconds (0.37s).
[2025-02-16T17:45:32.634+0000] {subprocess.py:106} INFO - [0m17:45:32
[2025-02-16T17:45:32.635+0000] {subprocess.py:106} INFO - [0m17:45:32  [32mCompleted successfully[0m
[2025-02-16T17:45:32.636+0000] {subprocess.py:106} INFO - [0m17:45:32
[2025-02-16T17:45:32.637+0000] {subprocess.py:106} INFO - [0m17:45:32  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-16T17:45:33.680+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-16T17:45:33.704+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T17:45:33.705+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_dm_categories_pivot_t, run_id=manual__2025-02-16T17:44:13.179593+00:00, execution_date=20250216T174413, start_date=20250216T174527, end_date=20250216T174533
[2025-02-16T17:45:33.751+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-16T17:45:33.769+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T17:45:33.771+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
