[2025-02-03T18:39:55.659+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-03T18:39:55.674+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.load_data scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-03T18:39:55.682+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.load_data scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-03T18:39:55.683+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-03T18:39:55.693+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-02-02 00:00:00+00:00
[2025-02-03T18:39:55.698+0000] {standard_task_runner.py:72} INFO - Started process 83 to run task
[2025-02-03T18:39:55.701+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'load_data', 'scheduled__2025-02-02T00:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpca38yfr9']
[2025-02-03T18:39:55.706+0000] {standard_task_runner.py:105} INFO - Job 153: Subtask load_data
[2025-02-03T18:39:55.761+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-03T18:39:55.824+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.load_data scheduled__2025-02-02T00:00:00+00:00 [running]> on host 64248ff56ecc
[2025-02-03T18:39:55.826+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-03T18:39:55.916+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T00:00:00+00:00'
[2025-02-03T18:39:55.918+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-03T18:39:59.099+0000] {base.py:84} INFO - Retrieving connection 'my_dwh_conn'
[2025-02-03T18:39:59.958+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-03T18:39:59.969+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-03T18:39:59.969+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=load_data, run_id=scheduled__2025-02-02T00:00:00+00:00, execution_date=20250202T000000, start_date=20250203T183955, end_date=20250203T183959
[2025-02-03T18:40:00.017+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-03T18:40:00.041+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-03T18:40:00.043+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
